/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PS_priprema_za_test_I.ui.form;

/**
 *
 * @author aleks
 */
public class FmrMain extends javax.swing.JFrame {

    /**
     * Creates new form FmrMain
     */
    public FmrMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuNastavnik = new javax.swing.JMenu();
        menuNastavnikItemAdd = new javax.swing.JMenuItem();
        menuNastavnikItemViewAll = new javax.swing.JMenuItem();
        Tabela2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuNastavnik.setText("Nastavnik");

        menuNastavnikItemAdd.setText("Add");
        menuNastavnikItemAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNastavnikItemAddActionPerformed(evt);
            }
        });
        menuNastavnik.add(menuNastavnikItemAdd);

        menuNastavnikItemViewAll.setText("View all");
        menuNastavnikItemViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNastavnikItemViewAllActionPerformed(evt);
            }
        });
        menuNastavnik.add(menuNastavnikItemViewAll);

        Tabela2.setText("jMenuItem1");
        Tabela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tabela2ActionPerformed(evt);
            }
        });
        menuNastavnik.add(Tabela2);

        jMenuBar1.add(menuNastavnik);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuNastavnikItemAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNastavnikItemAddActionPerformed
        new FrmAddNastavnik(null, true).setVisible(true);
    }//GEN-LAST:event_menuNastavnikItemAddActionPerformed

    private void menuNastavnikItemViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNastavnikItemViewAllActionPerformed
        new FrmViewAllNastavnici(null, true).setVisible(true);
    }//GEN-LAST:event_menuNastavnikItemViewAllActionPerformed

    private void Tabela2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tabela2ActionPerformed
        new FrmViewAddEditNastavnik(null, true).setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_Tabela2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Tabela2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuNastavnik;
    private javax.swing.JMenuItem menuNastavnikItemAdd;
    private javax.swing.JMenuItem menuNastavnikItemViewAll;
    // End of variables declaration//GEN-END:variables
}
